version: '3'

services:
    mongo:
        image: mongo
        ports:
            - "27018:27017"
        restart: always
        volumes: 
            - mongodb-volume:/data/db

    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        restart: always
        ports:
            - "8081:8081" 

    #chatbot_avfa:
    #    build:
    #        context: .
    #        dockerfile: Dockerfile
    #    depends_on: 
    #        - mongo
    #    environment:
    #        - ME_CONFIG_MONGODB_PORT=27018
    #    ports: 
    #        - "5000:5000"
    #        - "3000:3000"
    #    restart: always
    #    volumes: 
    #        - chatbot-avfa-volume:/usr/chatbot_avfa/public/resources

volumes: 
    mongodb-volume:
    chatbot-avfa-volume: